package pe.chalk.bukkit.pos

import org.bukkit.ChatColor
import org.bukkit.block.Biome

fun format(x: Int): String {
    return "${ChatColor.BOLD}${ChatColor.AQUA}$x${ChatColor.RESET}"
}

fun getBiomeName(biome: Biome): String {
    // from .minecraft/assets 1.16 (minecraft/lang/ko_kr.json)
    return when(biome.name.toLowerCase()) {
        "badlands" -> "악지 지형"
        "badlands_plateau" -> "악지 지형 고원"
        "bamboo_jungle" -> "대나무 정글"
        "bamboo_jungle_hills" -> "대나무 정글 언덕"
        "basalt_deltas" -> "현무암 삼각주"
        "beach" -> "해변"
        "birch_forest" -> "자작나무 숲"
        "birch_forest_hills" -> "자작나무 숲 언덕"
        "cold_ocean" -> "차가운 바다"
        "crimson_forest" -> "진홍빛 숲"
        "dark_forest" -> "어두운 숲"
        "dark_forest_hills" -> "어두운 숲 언덕"
        "deep_cold_ocean" -> "깊고 차가운 바다"
        "deep_frozen_ocean" -> "깊고 얼어붙은 바다"
        "deep_lukewarm_ocean" -> "깊고 미지근한 바다"
        "deep_ocean" -> "깊은 바다"
        "deep_warm_ocean" -> "깊고 따뜻한 바다"
        "desert" -> "사막"
        "desert_hills" -> "사막 언덕"
        "desert_lakes" -> "사막 호수"
        "end_barrens" -> "엔드 불모지"
        "end_highlands" -> "엔드 고지"
        "end_midlands" -> "엔드 중지"
        "eroded_badlands" -> "침식된 악지 지형"
        "flower_forest" -> "꽃 숲"
        "forest" -> "숲"
        "frozen_ocean" -> "얼어붙은 바다"
        "frozen_river" -> "얼어붙은 강"
        "giant_spruce_taiga" -> "거대 가문비나무 타이가"
        "giant_spruce_taiga_hills" -> "거대 가문비나무 타이가 언덕"
        "giant_tree_taiga" -> "거대 나무 타이가"
        "giant_tree_taiga_hills" -> "거대 나무 타이가 언덕"
        "gravelly_mountains" -> "자갈투성이 산"
        "ice_spikes" -> "역고드름"
        "jungle" -> "정글"
        "jungle_edge" -> "정글 변두리"
        "jungle_hills" -> "정글 언덕"
        "lukewarm_ocean" -> "미지근한 바다"
        "modified_badlands_plateau" -> "변형된 악지 지형 고원"
        "modified_gravelly_mountains" -> "자갈투성이 산+"
        "modified_jungle" -> "변형된 정글"
        "modified_jungle_edge" -> "변형된 정글 변두리"
        "modified_wooded_badlands_plateau" -> "변형된 나무가 우거진 악지 지형 고원"
        "mountain_edge" -> "산 변두리"
        "mountains" -> "산"
        "mushroom_field_shore" -> "버섯 들판 해안"
        "mushroom_fields" -> "버섯 들판"
        "nether_wastes" -> "네더 황무지"
        "ocean" -> "바다"
        "plains" -> "평원"
        "river" -> "강"
        "savanna" -> "사바나"
        "savanna_plateau" -> "사바나 고원"
        "shattered_savanna" -> "산산이 조각난 사바나"
        "shattered_savanna_plateau" -> "산산이 조각난 사바나 고원"
        "small_end_islands" -> "작은 엔드 섬"
        "snowy_beach" -> "눈 덮인 해변"
        "snowy_mountains" -> "눈 덮인 산"
        "snowy_taiga" -> "눈 덮인 타이가"
        "snowy_taiga_hills" -> "눈 덮인 타이가 언덕"
        "snowy_taiga_mountains" -> "눈 덮인 타이가 산"
        "snowy_tundra" -> "눈 덮인 툰드라"
        "soul_sand_valley" -> "영혼 모래 골짜기"
        "stone_shore" -> "돌 해안"
        "sunflower_plains" -> "해바라기 평원"
        "swamp" -> "늪"
        "swamp_hills" -> "늪 언덕"
        "taiga" -> "타이가"
        "taiga_hills" -> "타이가 언덕"
        "taiga_mountains" -> "타이가 산"
        "tall_birch_forest" -> "키 큰 자작나무 숲"
        "tall_birch_hills" -> "키 큰 자작나무 언덕"
        "the_end" -> "디 엔드"
        "the_void" -> "공허"
        "warm_ocean" -> "따뜻한 바다"
        "warped_forest" -> "뒤틀린 숲"
        "wooded_badlands_plateau" -> "나무가 우거진 악지 지형 고원"
        "wooded_hills" -> "나무가 우거진 언덕"
        "wooded_mountains" -> "나무가 우거진 산"
        else -> "[위치 링크를 표시할 수 없는 지역입니다]"
    }
}