package pe.chalk.bukkit.pos

import org.bukkit.ChatColor
import org.bukkit.block.Biome

fun format(x: Int): String {
    return "${ChatColor.BOLD}${ChatColor.AQUA}$x${ChatColor.RESET}"
}

fun getBiomeName(biome: Biome): String {
    // from .minecraft/assets 1.19.3 (minecraft/lang/ko_kr.json)
    return when(biome.name.toLowerCase()) {
        "badlands" -> "악지"
        "bamboo_jungle" -> "대나무 정글"
        "basalt_deltas" -> "현무암 삼각주"
        "beach" -> "해변"
        "birch_forest" -> "자작나무 숲"
        "cold_ocean" -> "차가운 바다"
        "crimson_forest" -> "진홍빛 숲"
        "dark_forest" -> "어두운 숲"
        "deep_cold_ocean" -> "깊고 차가운 바다"
        "deep_dark" -> "깊은 어둠"
        "deep_frozen_ocean" -> "깊고 얼어붙은 바다"
        "deep_lukewarm_ocean" -> "깊고 미지근한 바다"
        "deep_ocean" -> "깊은 바다"
        "desert" -> "사막"
        "dripstone_caves" -> "점적석 동굴"
        "end_barrens" -> "엔드 불모지"
        "end_highlands" -> "엔드 고지"
        "end_midlands" -> "엔드 중지"
        "eroded_badlands" -> "침식된 악지"
        "flower_forest" -> "꽃 숲"
        "forest" -> "숲"
        "frozen_ocean" -> "얼어붙은 바다"
        "frozen_peaks" -> "얼어붙은 봉우리"
        "frozen_river" -> "얼어붙은 강"
        "grove" -> "산림"
        "ice_spikes" -> "역고드름"
        "jagged_peaks" -> "뾰족한 봉우리"
        "jungle" -> "정글"
        "lukewarm_ocean" -> "미지근한 바다"
        "lush_caves" -> "무성한 동굴"
        "mangrove_swamp" -> "맹그로브 늪"
        "meadow" -> "목초지"
        "mushroom_fields" -> "버섯 들판"
        "nether_wastes" -> "네더 황무지"
        "ocean" -> "바다"
        "old_growth_birch_forest" -> "자작나무 원시림"
        "old_growth_pine_taiga" -> "소나무 원시 타이가"
        "old_growth_spruce_taiga" -> "가문비나무 원시 타이가"
        "plains" -> "평원"
        "river" -> "강"
        "savanna" -> "사바나"
        "savanna_plateau" -> "사바나 고원"
        "small_end_islands" -> "작은 엔드 섬"
        "snowy_beach" -> "눈 덮인 해변"
        "snowy_plains" -> "눈 덮인 평원"
        "snowy_slopes" -> "눈 덮인 비탈"
        "snowy_taiga" -> "눈 덮인 타이가"
        "soul_sand_valley" -> "영혼 모래 골짜기"
        "sparse_jungle" -> "듬성듬성한 정글"
        "stony_peaks" -> "돌 봉우리"
        "stony_shore" -> "돌 해안"
        "sunflower_plains" -> "해바라기 평원"
        "swamp" -> "늪"
        "taiga" -> "타이가"
        "the_end" -> "엔드"
        "the_void" -> "공허"
        "warm_ocean" -> "따뜻한 바다"
        "warped_forest" -> "뒤틀린 숲"
        "windswept_forest" -> "바람이 세찬 숲"
        "windswept_gravelly_hills" -> "바람이 세찬 자갈투성이 언덕"
        "windswept_hills" -> "바람이 세찬 언덕"
        "windswept_savanna" -> "바람이 세찬 사바나"
        "wooded_badlands" -> "나무가 우거진 악지"
        else -> "[위치 링크를 표시할 수 없는 지역입니다]"
    }
}